import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from "@react-pdf/renderer";
import type { Application, FeasibilityReport, FinancialBreakdown } from "@/types";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/Button";
import { Download } from "lucide-react";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#16262B" },
  title: { fontSize: 20, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 10, marginBottom: 20, color: "#3A5E64" },
  sectionTitle: { fontSize: 13, marginTop: 16, marginBottom: 6, fontFamily: "Helvetica-Bold", color: "#A54F22" },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  label: { color: "#3A5E64" },
  value: { fontFamily: "Helvetica-Bold" },
  paragraph: { marginBottom: 6, lineHeight: 1.4 },
  bullet: { marginBottom: 3, marginLeft: 8 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#3A5E64" }
});

function formatINR(value: number): string {
  return `Rs. ${new Intl.NumberFormat("en-IN").format(value)}`;
}

function BusinessPlanDocument({
  application,
  breakdown,
  report
}: {
  application: Application;
  breakdown: FinancialBreakdown;
  report: FeasibilityReport;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Business Feasibility & Financial Plan</Text>
        <Text style={styles.subtitle}>
          Prepared via Gram Vyapaar · {application.businessCategory} · Generated {new Date().toLocaleDateString("en-IN")}
        </Text>

        <Text style={styles.sectionTitle}>Financial Structure</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Margin contribution (10%)</Text>
          <Text style={styles.value}>{formatINR(breakdown.marginCapital)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Total project cost</Text>
          <Text style={styles.value}>{formatINR(breakdown.projectCost)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Loan eligibility (90%)</Text>
          <Text style={styles.value}>{formatINR(breakdown.loanAmount)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Scheme</Text>
          <Text style={styles.value}>{breakdown.scheme.name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Interest rate / Tenure / Moratorium</Text>
          <Text style={styles.value}>
            {breakdown.scheme.interestRatePct}% p.a. / {breakdown.scheme.tenureMonths / 12} yrs / {breakdown.scheme.moratoriumMonths} mo
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Market Reach</Text>
        <Text style={styles.paragraph}>{report.marketReach.summary}</Text>

        <Text style={styles.sectionTitle}>Opportunity Analysis</Text>
        <Text style={styles.paragraph}>{report.opportunityAnalysis.summary}</Text>

        <Text style={styles.sectionTitle}>SWOT Analysis</Text>
        <Text style={styles.value}>Strengths</Text>
        {report.swot.strengths.map((s) => (
          <Text key={s} style={styles.bullet}>• {s}</Text>
        ))}
        <Text style={styles.value}>Weaknesses</Text>
        {report.swot.weaknesses.map((s) => (
          <Text key={s} style={styles.bullet}>• {s}</Text>
        ))}
        <Text style={styles.value}>Opportunities</Text>
        {report.swot.opportunities.map((s) => (
          <Text key={s} style={styles.bullet}>• {s}</Text>
        ))}
        <Text style={styles.value}>Threats</Text>
        {report.swot.threats.map((s) => (
          <Text key={s} style={styles.bullet}>• {s}</Text>
        ))}

        <Text style={styles.sectionTitle}>Pricing Suggestion</Text>
        <Text style={styles.paragraph}>{report.pricingSuggestion.strategy}</Text>
        <Text style={styles.paragraph}>{report.pricingSuggestion.suggestedRangeNote}</Text>

        <Text style={styles.footer}>
          Generated by Gram Vyapaar — Ministry of Social Justice & Empowerment · Smart India Hackathon 2026 · PS 26091.
          This document is a feasibility aid and does not constitute a loan sanction.
        </Text>
      </Page>
    </Document>
  );
}

export function DownloadBusinessPlanButton({
  application,
  breakdown,
  report
}: {
  application: Application;
  breakdown: FinancialBreakdown;
  report: FeasibilityReport;
}) {
  const { t } = useTranslation();

  return (
    <PDFDownloadLink
      document={<BusinessPlanDocument application={application} breakdown={breakdown} report={report} />}
      fileName={`gram-vyapaar-business-plan-${application.id.slice(0, 8)}.pdf`}
    >
      {({ loading }) => (
        <Button disabled={loading}>
          <Download className="h-4 w-4" />
          {loading ? "..." : t("report.downloadPdf")}
        </Button>
      )}
    </PDFDownloadLink>
  );
}
